// 액션 타입 상수를 정의.

export const fetchActions = {
  FETCH_AUTO_DATA_REQUEST: 'FETCH_AUTO_DATA_REQUEST',
  FETCH_AUTO_DATA_SUCCESS: 'FETCH_AUTO_DATA_SUCCESS',
  FETCH_MEDIA_DATA_REQUEST: 'FETCH_MEDIA_DATA_REQUEST',
  FETCH_MEDIA_DATA_SUCCESS: 'FETCH_MEDIA_DATA_SUCCESS',
};

export const autoRollingActions = {
  START_AUTO_ROLLING: 'START_AUTO_ROLLING',
};

export const displayActions = {
  GRID_LEFT_BUTTON_CLICK: 'GRID_LEFT_BUTTON_CLICK',
  GRID_RIGHT_BUTTON_CLICK: 'GRID_RIGHT_BUTTON_CLICK',
  GRID_SUBSCRIBE_BUTTON_CLICK: 'GRID_SUBSCRIBE_BUTTON_CLICK',
  GRID_UNSUBSCRIBE_BUTTON_CLICK: 'GRID_UNSUBSCRIBE_BUTTON_CLICK',

  LIST_LEFT_BUTTON_CLICK: 'LIST_LEFT_BUTTON_CLICK',
  LIST_RIGHT_BUTTON_CLICK: 'LIST_RIGHT_BUTTON_CLICK',
  LIST_SUBSCRIBE_BUTTON_CLICK: 'LIST_SUBSCRIBE_BUTTON_CLICK',
  LIST_UNSUBSCRIBE_BUTTON_CLICK: 'LIST_UNSUBSCRIBE_BUTTON_CLICK',
  LIST_TAB_BUTTON_CLICK: 'LIST_TAB_BUTTON_CLICK',

  HEADER_LIST_BUTTON_CLICK: 'HEADER_ALL_LIST_BUTTON_CLICK',
  HEADER_GRID_BUTTON_CLICK: 'HEADER_ALL_GRID_BUTTON_CLICK',
  HEADER_ALL_MEDIA_BUTTON_CLICK: 'HEADER_ALL_MEDIA_BUTTON_CLICK',
  HEADER_MY_MEDIA_BUTTON_CLICK: 'HEADER_MY_MEDIA_BUTTON_CLICK',
};
